name: "PR Changelog Generator"
description: "Github action that creates a changelog on opening or updating the PR"
author: "Bala-raj"
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  token:
    required: true
    description: "As provided by Github Actions"
  branch:
    required: true
    description: "As provided by Github Actions"
  version:
    required: false
    description: "Current version"
outputs:
  next-version:
    description: "Next bumped version"   
  content:
    description: "Changes logs content"
runs:
  using: "node12"
  main: "dist/index.js"
